#markdown: rdiscount
permalink: /:title/
url: http://qingping209.github.io
highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: cnredis
author: qingping209
email: paralleld@qq.com
hub: qingping209
safe: false
