#markdown: rdiscount
permalink: /:title/
url: http://liangzong6.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: liangzong6
description: liangzong6
author: liangzong6
email: paralleld@qq.com
hub: liangzong6
safe: false
