#markdown: rdiscount
permalink: /:title/
url: http://paralleld.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: paralleld
description: paralleld | 多撸少BB
author: paralleld
email: paralleld@qq.com 
duoshuo: dwj
weibo: 1859819624
hub: paralleld
safe: false
about: "老码农"
