# Site settings
title: Paralleld Notes
email: parallel#qq.com (Oh yes, I love qq mail)
description: I'd like to leave this blank 
baseurl: "" 
url: "http://paralleld.com" 
github_username: paralleld
# Build settings
markdown: kramdown
